### PR TITLE
Update pedrovsrr.md

### PR DESCRIPTION
**Pull request by j5155**
Fixes credit to be visible, as well as fixing some factual errors

### CODE REVIEW

**Comment by j5155** [comment]
I also added a link to the Cookbook version of the article. I am happy to add a link from the Cookbook version to this one as well, after this PR is merged.

**Comment by j5155** [comment]
And I permit both the original work and these changes to be licensed under the BSD-3-Clause license just added to this repo, and/or the MIT License of the Cookbook version.

**Comment by j5155** [comment]
@BaronClaps would you consider reopening the PR?
I'd be happy to discuss any changes you disagree with. 
I'd prefer if it was merged instead of the changes copied and pasted over, so that the changes are properly attributed to me in the commit history.

**Comment by BaronClaps** [comment]
I decided to not merge your pr because that is not the direction we are going. I added a table to better show the pros and cons. I only removed the `- Forced to use Actions and blocking` after your persistent request to move it (even though i rewrote it say `- Default RR1.0 configurations enforce blocking actions`. Otherwise, all changes I have made were on my own volition and not created to avoid this pr.

**Pull request closed without merging**
